let stockProductos = [
    {id: 1, freeshipping: false, nombre: "Buzo 1", tipo: "buzo", desc: "Un buzo que re va con vos", precio: 1200, talle: "L", img: './img/buzo.jpg'},
    {id: 2, freeshipping: true, nombre: "Buzo 2", tipo: "buzo", desc: "Un buzo que re va con vos", precio: 1100, talle: "L", img: './img/buzo.jpg'},
    {id: 3, freeshipping: false, nombre: "Buzo 3", tipo: "buzo", desc: "Un buzo que re va con vos", precio: 1200, talle: "M", img: './img/buzo.jpg'},
    {id: 4, freeshipping: false, nombre: "Buzo 4", tipo: "buzo", desc: "Un buzo que re va con vos", precio: 1400, talle: "M", img: './img/buzo.jpg'},
    {id: 5, freeshipping: false, nombre: "Buzo 5", tipo: "buzo", desc: "Un buzo que re va con vos", precio: 1200, talle: "S", img: './img/buzo.jpg'},
    {id: 6, freeshipping: true, nombre: "Buzo 6", tipo: "buzo", desc: "Un buzo que re va con vos", precio: 1500, talle: "S", img: './img/buzo.jpg'},
    {id: 7, freeshipping: false, nombre: "Remera 1", tipo: "remera", desc: "Una remera que re va con vos", precio: 500, talle: "L", img: './img/remera.jpg'},
    {id: 8, freeshipping: false, nombre: "Remera 2", tipo: "remera", desc: "Una remera que re va con vos", precio: 500, talle: "L", img: './img/remera.jpg'},
    {id: 9, freeshipping: true, nombre: "Remera 3", tipo: "remera", desc: "Una remera que re va con vos", precio: 500, talle: "M", img: './img/remera.jpg'},
    {id: 10, freeshipping: false, nombre: "Remera 4", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "M", img: './img/remera.jpg'},
    {id: 11, freeshipping: true, nombre: "Remera 5", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "S", img: './img/remera.jpg'},
    {id: 12, freeshipping: false, nombre: "Remera 6", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "S", img: './img/remera.jpg'},
    {id: 13, freeshipping: false, nombre: "Camisa 1", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 900, talle: "L", img: './img/camisa.jpg'},
    {id: 14, freeshipping: false, nombre: "Camisa 2", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 1400, talle: "S", img: './img/camisa.jpg'},
    {id: 15, freeshipping: true, nombre: "Camisa 3", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 7000, talle: "L", img: './img/camisa.jpg'},
    {id: 16, freeshipping: false, nombre: "Camisa 4", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 777, talle: "S", img: './img/camisa.jpg'},
    {id: 17, freeshipping: false, nombre: "Camisa 5", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 234, talle: "S", img: './img/camisa.jpg'},
    {id: 18, freeshipping: false, nombre: "Camisa 6", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 155600, talle: "M", img: './img/camisa.jpg'},
    {id: 19, freeshipping: false, nombre: "Pantalon 1", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 1600, talle: "L", img: './img/pantalon.jpg'},
    {id: 20, freeshipping: true, nombre: "Pantalon 2", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 3200, talle: "L", img: './img/pantalon.jpg'},
    {id: 21, freeshipping: false, nombre: "Pantalon 3", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 2300, talle: "M", img: './img/pantalon.jpg'},
    {id: 22, freeshipping: true, nombre: "Pantalon 4", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 5600, talle: "M", img: './img/pantalon.jpg'},
    {id: 23, freeshipping: false, nombre: "Pantalon 5", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './img/pantalon.jpg'},
    {id: 24, freeshipping: false, nombre: "Pantalon 6", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './img/pantalon.jpg'},
]
